language: node_js

node_js:
  - 'stable'

notifications:
    slack: zeitteam:sYG58AkS6aJBsN8cLirAtL9E

before_deploy:
  - npm install -g grunt-cli

deploy:
  provider: script
  script:
    - 'echo "TODO: deploy the app. Directory listing:" && ls -R dist'
  skip_cleanup: true
  on:
    branch: master